### ISSUE TITLE
MM Logo broken.

### ISSUE THREAD

**Issue by ZaighumRajput** [mar-ii-a/mar-ii-a.github.io#1]
Hi Maria, 
Apologies for the request. 
It seems that after the recent push. 
The logo has broken.

Can you please assist.

**Comment by mar-ii-a** [comment]
This will be resolved shortly, apologies

**Comment by ZaighumRajput** [comment]
Hi Maria, 
Thank you for the prompt response. 

Although, I haven't seen any changes. Can I kindly request that we keep the issue open till then?
I am having difficulty on my end. 

Appreciate your attention and help. 
Keep up the great work!
