### ISSUE TITLE
update project page

### ISSUE THREAD

**Issue by CLRiosNA** [mar-ii-a/mar-ii-a.github.io#8]
Hello,

We need to update/create a project page based on the design markup.

Please note that this is a critical step in the design and the team requires these updates before continuing work.

Nav

@ZaighumRajput 
@mar-ii-a

**Comment by CLRiosNA** [comment]
design schema will soon be available in the report, please stand by

**Comment by ZaighumRajput** [comment]
Hi CLRiosNA,
Cool name by the way.

I'm sorry but I don't quit understand the task.
I am more than happy to help, but if you could clarify a tiny bit further, it would be much appreciated.

**Comment by ZaighumRajput** [comment]
Hi when can I expect the design?

**Comment by ZaighumRajput** [comment]
Hi Naveed, 
Sorry to be a pest; could I please get a status update?
